import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

import { Group } from "@/types";
import { saveGroup } from '@/hooks/use-firestore';

interface CreateGroupModalProps {
  open: boolean;
  onClose: () => void;
  onCreated: () => void;
  userId: string; // 🔴 REQUIRED NOW
}

const CreateGroupModal = ({
  open,
  onClose,
  onCreated,
  userId,
}: CreateGroupModalProps) => {
  const [name, setName] = useState("");
  const [membersText, setMembersText] = useState("");
  const [includeYou, setIncludeYou] = useState(true);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !userId) return;

    const memberNames = membersText
      .split(",")
      .map((m) => m.trim())
      .filter(Boolean);

    if (includeYou && !memberNames.includes("You")) {
      memberNames.unshift("You");
    }

    if (memberNames.length < 2) return;

    try {
      setLoading(true);

      const groupData: Omit<Group, 'id'> = {
        name: name.trim(),
        members: memberNames,
        expenses: [],
        createdAt: Date.now(),
        shareCode: '' // will be generated by server/hook
      };

      await saveGroup(groupData, userId);

      onCreated();
      handleClose();
    } catch (err) {
      console.error("Failed to create group", err);
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setName("");
    setMembersText("");
    setIncludeYou(true);
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-md max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-xl">
            Create New Group
          </DialogTitle>
          <DialogDescription>
            Enter the details for your new squad or trip to start splitting bills.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-6 mt-4">
          <div className="space-y-2">
            <Label htmlFor="groupName">Group Name</Label>
            <Input
              id="groupName"
              placeholder="e.g., Goa Trip 2024"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="h-12"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="members">Member Names</Label>
            <Textarea
              id="members"
              placeholder="Rahul, Priya, Amit"
              value={membersText}
              onChange={(e) => setMembersText(e.target.value)}
              className="min-h-[100px] resize-none"
            />
            <p className="text-xs text-muted-foreground">
              Separate names with commas
            </p>
          </div>

          <div className="flex items-center gap-3">
            <Checkbox
              id="includeYou"
              checked={includeYou}
              onCheckedChange={(checked) =>
                setIncludeYou(Boolean(checked))
              }
            />
            <Label
              htmlFor="includeYou"
              className="text-sm font-normal cursor-pointer"
            >
              Include "You" as a member
            </Label>
          </div>

          <div className="flex gap-3 pt-2">
            <Button
              type="button"
              variant="outline"
              onClick={handleClose}
              className="flex-1"
              disabled={loading}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              className="flex-1"
              disabled={loading}
            >
              {loading ? "Creating..." : "Create Group"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default CreateGroupModal;
